### ISSUE TITLE
Redis 6.2 New Commands Check List

### ISSUE THREAD

**Issue by 2014BDuck** [andymccurdy/redis-py#1434]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: Redis 6.2

**Platform**: N/A

**Description**: Check Redis 6.2 RC [Release Note](https://github.com/redis/redis/blob/b8c67ce41b51247c02a639929e4fab20189afa1e/00-RELEASENOTES) and update missing commands

Commands new in Redis 6.2:
- [ ] Add SMISMEMBER command that checks multiple members [(#7615)](https://github.com/redis/redis/pull/7615)
- [x] Add ZMSCORE command that returns an array of scores [(#7593)](https://github.com/redis/redis/pull/7593)
- [ ] Add LMOVE and BLMOVE commands that pop and push arbitrarily [(#6929)](https://github.com/redis/redis/pull/6929)
- [ ] Add RESET command that resets client connection state[(#7982)](https://github.com/redis/redis/pull/7982)
- [ ] Add COPY command that copies keys [(#7953)](https://github.com/redis/redis/pull/7953)
- [ ] Add ZDIFF and ZDIFFSTORE commands [(#7961)](https://github.com/redis/redis/pull/7961)
- [ ] Add ZINTER and ZUNION commands [(#7794)](https://github.com/redis/redis/pull/7794)
- [ ] Add GEOSEARCH/GEOSEARCHSTORE commands for bounding box spatial queries [(#8094)](https://github.com/redis/redis/pull/8094)
- [x] Add GET parameter to SET command, for more powerful GETSET [(#7852)](https://github.com/redis/redis/pull/7852)
- [ ] Add exclusive range query to XPENDING [(#8130)](https://github.com/redis/redis/pull/8130)
- [ ] Add exclusive range query to X[REV]RANGE [(#8072)](https://github.com/redis/redis/pull/8072)
- [ ] Add GT and LT options to ZADD for conditional score updates [(#7818)](https://github.com/redis/redis/pull/7818)
- [ ] Add CLIENT INFO and CLIENT LIST for specific ids [(#8113)](https://github.com/redis/redis/pull/8113)
- [ ] Add IDLE argument to XPENDING command [(#7972)](https://github.com/redis/redis/pull/7972)
- [ ] Add local address to CLIENT LIST, and a CLIENT KILL filter. [(#7913)](https://github.com/redis/redis/pull/7913)
- [ ] Add NOMKSTREAM option to XADD command [(#7910)](https://github.com/redis/redis/pull/7910)
- [ ] Add command introspection to Sentinel [(#7940)](https://github.com/redis/redis/pull/7940)
- [ ] Add SENTINEL MYID subcommand [(#7858)](https://github.com/redis/redis/pull/7858)

**Comment by 2014BDuck** [comment]
Would like to raise an issue for tracking what we missed and add them one by one.

**Comment by trulede** [comment]
ZMSCORE seems to be missing?

**Comment by shreybatra** [comment]
Hi @andymccurdy, the above list shows the commands missing in current redis-py and supported by redis v6.2 right? Can we contribute to add these? If yes, can you please tell if we need to raise a PR to the master branch itself?

**Comment by 2014BDuck** [comment]
> Hi, the above list shows the commands missing in current redis-py and supported by redis v6.2 right? Can we contribute to add these? If yes, can you please tell if we need to raise a PR to the master branch itself?

Would need to check one by one. 

I think most of them are missing right now. You can mention this issue in your PRs so that others could check the mentioned records and  know which one is done

**Comment by LastSun** [comment]
xadd(self, name, fields, id='*', maxlen=None, approximate=True) change all fields value data type to string, is it correct?

**Comment by needs** [comment]
[ZRANDMEMBER](https://redis.io/commands/zrandmember) seems to be missing?

**Comment by chayim** [comment]
Closing in favour of #1546. It's canonical. If you see any missing there, please update!
